### ISSUE TITLE
log4js test failing - and fix

### ISSUE THREAD

**Issue by ghost** [lorenwest/node-monitor#1]
In 
7-log4js-logger-test.js

change 
var log4js = deps.log4js;

to 
var log4js = deps.log4js();

This matches the log4js docs.

**Comment by lorenwest** [comment]
Apparently the log4js package was updated, and not made backwardly compatible.  I've made this change and bumped the version in the npm repository.  A 'npm update monitor' should resolve the issue.  Thanks for catching this!
