### ISSUE TITLE
Support for HTTP monitoring?

### ISSUE THREAD

**Issue by rainmaker-ac** [lorenwest/node-monitor#19]
Hello,

I apologize for asking this question here but I couldn't find another way to ask you this as this really isn't an "issue".

I'm curious, is there a way to do HTTP monitoring on here or would that require me to create my own my own data probe and monitor probe? For example, I would like to connect to a server via HTTP and do things like ping and request various logs (the app/server I would connect to is not a node.js app). From there, I would parse them, display them on screen, throw up warnings and errors, get those values from the logs to populate the gauges, etc.

BTW, love the work you have done. Looks fantastic!

Thanks!

**Comment by lorenwest** [comment]
No problems asking questions on this forum.  

Node-monitor lets you build pages with all kinds of different monitors.  In your case, you would probably put up an endpoint on your server to send logs of various kinds to the front end.  Each monitor page has a settings screen (page settings on the menu) where you can put javascript to run when the page is loaded.

The way I'd go about doing this is to request these logs on page load, and place the log data into a globally accessible variable.  From there I would drop a few widgets on the screen for viewing this data.  Maybe a graph widget or two that visualizes the data in different ways.  Maybe an HTML widget that looks at the logs and produces some HTML to display based on it's findings.

After you've got a few of these pages, tie them together using a tour.  When the tour is run it will cycle through the pages you've created.  We put tours onto monitors throughout our company - one cycles through business data for our business team, another cycles through logs and server stats for our technical team.
