### ISSUE TITLE
couchdb test failing - wrong module?

### ISSUE THREAD

**Issue by ghost** [lorenwest/node-monitor#2]
What is the correct "couchdb" module?

**Comment by lorenwest** [comment]
Thank you for noticing.  The couchdb NPM module is no longer supported, and was removed from the npm repository.  Someone else placed their own couchdb module in it's place, and it's not compatible.  After doing some research and testing, the couchdb logger was modified to use the 'couch-client' package.  It's now listed in the package.json, and the version was bumped, so an 'npm update monitor' should load the correct packages.

**Comment by ghost** [comment]
Thanks for the fixes. All tests passing. And thanks for node-monitor and node-config.
