### ISSUE TITLE
Troubles running example scripts on Mac

### ISSUE THREAD

**Issue by owntheweb-archive** [lorenwest/node-monitor#22]
This may be a replay issue from when I was exploring the dashboard here (I appoligize in advance if this is a repeat!):
https://github.com/lorenwest/monitor-dashboard/issues/4

Running Mac OS X 10.9.1, I cd to my clean project directory and install node-monitor:

```
sudo npm install monitor
```

A new 'node_modules' folder appears with a 'monitor' folder and files there, cool!

keeping Terminal open, I attempt this:

```
$ node
> var Monitor = require('monitor');
undefined
```

It returns 'undefined'. Now, if I run this instead:

```
var Monitor = require('./node_modules/monitor/monitor.js');
```

I get this:

```
> Monitor service started on host: localhost

External connections disabled.
See /Users/owntheweb/Documents/personal/statMonitor/server/gatherer/config/external.js for more information.
```

Cool! So moving on to the example low memory alert in low-memory-warn.js, if I run the example as-is, it runs without error and exits immediately, not printing anything in Terminal. If I alter it to match the above require line, errors occur.

Here's the altered low-memory-warn.js script:

```
// Low memory warning monitor
//var Monitor = require('monitor'); //THIS PRODUCES NOTHING, APP RUNS WITHOUT ERROR, EXITS IMMEDIATELY
var Monitor = require('./node_modules/monitor/monitor.js'); //THIS RESULTS IN ERRORS
var LOW_MEMORY_THRESHOLD = 100000000;

// Set the probe to push changes every 10 seconds
var options = {
  hostName: 'localhost',
  probeClass: 'Process',
  initParams: {
    pollInterval: 10000
  }
}
var processMonitor = new Monitor(options);

// Attach the change listener
processMonitor.on('change', function() {
  var freemem = processMonitor.get('freemem');
  if (freemem < LOW_MEMORY_THRESHOLD) {
    console.log('Low memory warning: ' + freemem);
  }
});

// Now connect the monitor
processMonitor.connect(function(error) {
  if (error) {
    console.error('Error connecting with the process probe: ', error);
    process.exit(1);
  }
});
```

Here's the result:

```
                        __________
_______ ___________________(_)_  /______________ 
__  __ `__ \  __ \_  __ \_  /_  __/  __ \_  ___/
_  / / / / / /_/ /  / / /  / / /_ / /_/ /  /
/_/ /_/ /_/\____//_/ /_//_/  \__/ \____//_/

[2014-02-20T16:36:17.473Z] [FATAL] monitor.moniotor.uncaught - Uncaught Exception: object is not a function
[2014-02-20T16:36:17.475Z] [FATAL] monitor.moniotor.uncaught - TypeError: object is not a function
    at Object.<anonymous> (/Users/owntheweb/Documents/personal/statMonitor/server/gatherer/low-memory-warn.js:14:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

Here's line 14:

```
var processMonitor = new Monitor(options);
```

Any thoughts on what I might be doing wrong? I understand that MacOS may be a bit touchy. If I need to move all this to a Linux machine (my final project will be on Linux), let me know.

Thanks for the feedback in advance!

**Comment by lorenwest** [comment]
Hey Christopher,

The initial command was working as expected:

```
$ node
> var Monitor = require('monitor');
undefined
```

`undefined` is actually what the REPL displays whenever you assign a variable.  Try this:

```
$ node
var a = 'hello';
undefined
```

From that point on, things went downhill fast.  Running `require('./node_modules/monitor/monitor.js');` starts the monitor server (cool!).  It's the same as going into the monitor directory and entering

```
$ node monitor.js
```

Unfortunately this isn't the same as `var Monitor = require('monitor');` because it doesn't assign the Monitor class to your variable.  From that point on, the `Monitor` variable doesn't represent a class that you can `new`, so things didn't work very well.

Try running the commands in the REPL window just as they're shown in the example.  I will update the example to show the `undefined` return from the first command, because I can see how this can be confusing.

**Comment by owntheweb-archive** [comment]
Aha! I should have known better. Thanks for working with a newb. ;)

The REPL example is working great! I'm seeing a memory change reported every second. The JSON data is exactly what I'm after for my custom app.

AHA! I figured it out. In the documented js example:

```
var Monitor = require('monitor');
```

needs to change to:

```
var Monitor = require('monitor').start();
```

Then I'm seeing stuff after adding a few test log messages (showing onchange being fired every 10 seconds as expected!).

Would you like me to attempt a pull-request? :dancer: 

Thanks again.

**Comment by lorenwest** [comment]
Adding `.start()` to the end of `require('monitor')` starts the monitor server within the REPL, which is cool, but not necessary for this client-side example.  The `start()` command is necessary in your server, which should be running in another process while running the client-side example.

Does this make sense?

**Comment by owntheweb-archive** [comment]
Yes, I think that makes sense. Since I'm creating a server script and not something that would run in the browser client (my server will talk to the browser client with this info and details from other services), I need to start it for the server. The client that connects to my server will not need that (and actually won't use it directly in my case). 

Thanks for the clarification and assist!

**Comment by owntheweb-archive** [comment]
I'll go ahead and close this.
