### ISSUE TITLE
error running monitor

### ISSUE THREAD

**Issue by morenoh149** [lorenwest/node-monitor#25]
trying to run monitor on my machine before install this project via npm gave me a complaint about java. Then I did

```
 git:(master) which monitor
/Users/harrymoreno/programming/android/adt-bundle/sdk/tools/monitor
```

so another application named monitor exists. What's the best way to try out `node-monitor` ?

**Comment by lorenwest** [comment]
Hi Harry,

node-monitor is a library that runs within your node.js application.  It doesn't install an executable on your operating system.  The best way to try it out is to follow the quick start guide on the [README](https://github.com/lorenwest/node-monitor) page.

Cheers,
-Loren

**Comment by morenoh149** [comment]
mmm nope. I ran `npm install monitor` in my existing node application. When I run `monitor` it's still calling the monitor program installed on my machine. I bet the terminal searches through the path before attempting to run from node_modules

**Comment by lorenwest** [comment]
The node-monitor library doesn't install an executable named `monitor`.  It's a library that runs within your node.js application.

If you type `monitor` into your terminal, you aren't going to get node-monitor.  To try node-monitor, you have to embed it into your node.js application by following the instructions on the README page.

**Comment by morenoh149** [comment]
ah a misunderstanding of what this is
