### ISSUE TITLE
Error watching for file (runtime.json) ENOSPC

### ISSUE THREAD

**Issue by fed135** [lorenwest/node-monitor#27]
Hey guys,

Just installed the package and I got some weird error when I start my application.

I've isolated the faulty line to this (I don't even do anything with it): 

```
var Monitor = require('monitor');
```

The error being : 

```
Error watching for file: /home/fcharette/Documents/workspace/gap-telemetry/config/runtime.json { [Error: watch ENOSPC] code: 'ENOSPC', errno: 'ENOSPC', syscall: 'watch' }
```

monitor version from npm, v0.6.10

I run iojs v1.8.2, npm 2.9.0
I'm on Ubuntu 15
I have plenty of space on my disk (and on /tmp)

Any ideas ?
Thank you!

**Comment by lorenwest** [comment]
A quick search on `ENOSPC` shows you have no space left on your device.  The runtime.json file is probably being watched from the `node-config` dependency.

**Comment by fed135** [comment]
As mentionned, plenty of space:

Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M   18M  781M   3% /run
/dev/sda1       111G   14G   91G  14% /
tmpfs           3.9G  444K  3.9G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           798M   56K  798M   1% /run/user/1000

Even changed my tmp path in npm config to /var/logs

Looking into the config package, I see where it does the watch, still unsure why there is an error though.

**Comment by fed135** [comment]
According a couple bug reports surrounding fs.watch and ENOSPC, it seems like the issue is that the limit for simultaneous file watches has been reached.

I rebooted and now everything seems to run fine.
Not entirely sure where the other file watches were coming from, had no other node process opened.

Oh well, you could maybe add a note about this somewhere.

FYI: I like to know what the libraries I require do behind my back. And preferably, I like them to not do anything behind my back.
