### ISSUE TITLE
npm package.json strings are not quoted

### ISSUE THREAD

**Issue by ryanbreen** [lorenwest/node-monitor#3]
It appears that node 0.4.0 and node 0.5.0-pre are more particular in the JSON they will allow.  Attempting to npm install monitor with those versions yields this:

Ryans-17-MBP-2:node wrb$ npm install monitor
npm ERR! couldn't read package.json in /var/folders/zH/zHPL9C4QGLyyHkzBTjnp1k+++TI/-Tmp-/npm-1298045898236/1298045898236-0.22087552351877093/contents/package
npm ERR! Error installing monitor@0.2.9
npm ERR! Error: Failed to parse json
npm ERR! Unexpected token ILLEGAL
npm ERR! {
npm ERR! name: "monitor",
npm ERR! version: "0.2.9",
npm ERR! main: "./lib/node-monitor.js",
npm ERR! description: "Runtime monitoring for node.js applications",
npm ERR! author: "Loren Westopen_source@lorenwest.com",
npm ERR! directories: {lib: "./lib", test: "./test"},
npm ERR! modules: {
npm ERR! "console-logger": "./logger/console-logger",
npm ERR! "file-logger": "./logger/file-logger",
npm ERR! "log4js-logger": "./logger/log4js-logger",
npm ERR! "os-cmd-logger": "./logger/os-cmd-logger",
npm ERR! "email-logger": "./logger/email-logger",
npm ERR! "couchdb-logger": "./logger/couchdb-logger"
npm ERR! },
npm ERR! dependencies: {
npm ERR! "config": ">=0.2.8",
npm ERR! "sprintf": ">=0.1.1",
npm ERR! "vows": ">=0.5.6",
npm ERR! "log4js": ">=0.2.3",
npm ERR! "couch-client": ">=0.0.3"
npm ERR! },
npm ERR! engines: {"node": ">=0.2.4"},
npm ERR! scripts: {
npm ERR! test: "vows test/.js --spec"
npm ERR! }
npm ERR! }
npm ERR!
npm ERR! at /usr/local/lib/node/.npm/npm/0.3.0-8/package/lib/utils/read-json.js:73:13
npm ERR! at P (/usr/local/lib/node/.npm/npm/0.3.0-8/package/lib/utils/read-json.js:62:40)
npm ERR! at cb (/usr/local/lib/node/.npm/npm/0.3.0-8/package/lib/utils/graceful-fs.js:31:9)
npm ERR! at [object Object]. (fs.js:86:5)
npm ERR! at [object Object].emit (events.js:39:17)
npm ERR! at afterRead (fs.js:840:12)
npm ERR! Report this entire\* log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm not ok

If I quote each string in that file, JSON.parse works.

**Comment by lorenwest** [comment]
Thank you for the find.  I'll update the package this weekend.

**Comment by lorenwest** [comment]
Updated the package to work with the more strict JSON parser.  Thanks again for pointing this out!
