### ISSUE TITLE
How can I add additional data to the monitor result?

### ISSUE THREAD

**Issue by JohnPekl** [lorenwest/node-monitor#33]
Hi,

As I know, this module use socket to communicate between a remote server and a server to be measured, and I can get data from this command `processMonitor.toJSON();`. How can I utilize the socket connection or the JSON file format to add my data? For example, I can add a list of files in a specified folder to the JASON file before sending to the remote server.

Thank you in advance.

**Comment by lorenwest** [comment]
`processMonitor` is a reference to a remote probe, written for the purpose of monitoring the process aspects of a remote server. You could write your own probe, say, `temperatureMonitor`, and that probe could contain the temperature of the remote server.

So the answer to your question - the probe running on the remote server defines the data in the JSON object. Change the probe, and you'll change the data in that object. You could change one of the existing probes, extend it, or write a probe for yourself.

Good luck!

**Comment by JohnPekl** [comment]
Please give me an example of a Probe. (For example: http://lorenwest.github.io/node-monitor/doc/classes/Probe.html).

Whenever I use ping_control()/onControl, it has an error: ping_control/onControl is not a function.

Thank for your help.

**Comment by lorenwest** [comment]
The left hand panel of the Probe.html page has a list of many different examples of probes. The documentation connects directly with the code so you can see how working probes are built.

Here's an example of a few probes on a dashboard: http://lorenwest.github.io/monitor-dashboard/pages/overview/dashboards.html

I can't provide consulting, so I hope these examples provide enough guidance.

**Comment by JohnPekl** [comment]
I have spent two days on what you told me, but it is difficult to understand the Probe.
Whenever I run a server, It appears an error _[2017-02-21T06:31:29.106Z] [ERROR] Monitor.control.Process.ping - Probe not connected_ 

**Monitor App:**

var Monitor = require('monitor'); 
var LOW_MEMORY_THRESHOLD = 100000000;
// Set the probe to push changes every 10 seconds
var options = {
  hostName: '192.168.1.70',
  probeClass: 'Process',
  initParams: {
    pollInterval: 10000
  }
}
var processMonitor = new Monitor(options);
// Attach the change listener
processMonitor.on('change', function() {
});
// Now connect the monitor
processMonitor.connect(function(error) {
  if (error) {
    console.error('Error connecting with the process probe: ', error);
    process.exit(1);
  }
});
// Remote control
processMonitor.control('ping', function(error, response) {
  console.log('Ping response: ', response);
});

**Server to be monitored:**
var Monitor = require('monitor');
var serverMon = new Monitor.Server(options);
serverMon.on('start', function() {
console.log("Server Started...");
});
var options = {
  probeClass: 'Process',
  initParams: {
    pollInterval: 10000
  }
}
var Probe = new Monitor.Probe(options);
Probe.ping_control('ping',function(error, content) {
  console.log("ping_control: " + content + ', ' + error);
});
//Probe.start();
//console.log(this.probe.get('probeClass'));
serverMon.start();

How to connect probes?
Please help me out!!
