### ISSUE TITLE
Please add at least one example 

### ISSUE THREAD

**Issue by krstns** [lorenwest/node-monitor#6]
Hi,

I would really like to use node-monitor module, however I can't get it to connect to my process.
I've included require("monitor-min").start() in my project, and I would like to start the node-monitor on the same server to add some charts and monitor it.
To be honest... I have got no clue on how to add a chart to monitor for example memory usage.
A single example would be awesome!

Thanks

**Comment by lorenwest** [comment]
Hello krstns,

Yes!  I can't agree with you more.  Node-monitor is code complete, but without docs (even the basics), it's not very useful.  Considering documentation _is_ code, I can't really say it's code complete.

If I could manufacture more hours in the day, this would already be complete.  It's moving forward at a slow but steady pace, so until it's published the best thing to do is play with it.  Have you tried adding a REPL component to a new page?  You can add a new page just by navigating to an URL that doesn't exist.

Then keep an eye out for a documentation release.

Best,
-Loren

**Comment by lorenwest** [comment]
Node-monitor just got a facelift with 0.6.x.  See the new online docs.  It's still a bit shy on examples, but the big picture documentation is in place now.
